import Head from "next/head";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <link rel="shortcut icon" href="#" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex">
        <div className="flex">TEST</div>
      </main>
    </>
  );
}
